### ISSUE TITLE
Request: Hook x86 and x64 process from a single application.

### ISSUE THREAD

**Issue by alainhb2000** [EasyHook/EasyHook#142]
I've made an application (A) that hooks another app (B), and one of the hooks i've done is that when the app (B) executes a new process (CreateProcessA, CreateProcessW) it notifies to app (A) using the interface, then in the app (A) i'm using Inject method to hook the new process created in app (B) with the same Dll i've injected to app (B), when the process is 32bit all works fine, the problem is when app (B) executes a 64 bit process, it throws an exception telling this:
STATUS_NO_MEMORY: Unable to allocate memory in target process. (Code: 5)

What i see is that easyhook is not starting the 64 bit service to hook the new process, it's already trying to inject the dll using 32bit service.

When i manually start this 64 bit process, using CreateAndInject method, from start, with any other hooks, it works fine, and the 64 bit easy hook service starts ok too.

Please some one can tell me what i'm missing, or if this has another solution.
Best regards
 Alain

**Comment by spazzarama** [comment]
Is app (A) 32- or 64-bit?

**Comment by alainhb2000** [comment]
Well, I have app (A) compiled using Any CPU profile.

**Comment by spazzarama** [comment]
@alainhb2000 it will only use the service app if necessary to work around the WOW64 boundary.

**Comment by alainhb2000** [comment]
Any suggestions ???

**Comment by spazzarama** [comment]
@alainhb2000 have you tried other 64-bit targets? Does it always happen for every 64-bit target process?

Btw, not being able to reserve memory in a remote process is a common anti-injection technique. Upon checking the windows error code 5 [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx) it is an ERROR_ACCESS_DENIED.

If it is all 64-bit processes that are failing (e.g. Notepad.exe as well), then it might be necessary to prepare a cut-down project so that I can reproduce the scenario here and assist further.

**Comment by alainhb2000** [comment]
I'll send you a PM, with more details. Thanks.
