### ISSUE TITLE
It is unable to intercept WriteFile API from an executable which is in C language.

### ISSUE THREAD

**Issue by bupt213209** [EasyHook/EasyHook#147]
I am new to EasyHook. I have already hooked a WriteFile API successfully by injecting the dll into a notepad.exe using EasyHook. However, when I turn to intercepting the WriteFile API by injecting the dll into an executable (C program), which is programmed by myself, it does not work. I have experimented with the WriteFile, WriteFileEx, and WriteFileGather API respectively, but they all fails. It baffles me that it does not work on an  executable while it works on notepad.exe. Can anyone help me fix this? Any help will be appreciated.

The executable (C program), namely the target, is shown as follows.

#include <stdio.h>
int main ()
{
    FILE * pFile;
    char buffer[] = { 'x' , 'y' ,'z'};
    pFile = fopen ("output.txt", "wb");
    fwrite (buffer , sizeof(char), sizeof(buffer), pFile);
    fclose (pFile);
    return 0;
}

**Comment by spazzarama** [comment]
Are you using CreateAndInject?

**Comment by spazzarama** [comment]
Hooking in this manner does work (i.e. C program as target), I'm going to assume that either fwrite has been called before the injection or it doesn't actually call the API that you think it does.

For this test, either add a system("pause"); at the start and wait for injection, or use CreateAndInject to ensure the hooks are in place before the target method is called. I would also test calling WriteFile directly, instead of fwrite as I'm not sure if that results in a call to WriteFile under the hood.
