### ISSUE TITLE
Build fails on win10.0.16299.0 SDK 

### ISSUE THREAD

**Issue by atkawa7** [EasyHook/EasyHook#225]
Building fails on visual studio
```c++
typedef struct _CLIENT_ID
{
    DWORD	    UniqueProcess;
    DWORD	    UniqueThread;
}CLIENT_ID, * PCLIENT_ID;
```

`Error	C2011	'_CLIENT_ID': 'struct' type redefinition	EasyHookDll
debug.cpp	73`

**Comment by spazzarama** [comment]
Confirmed doesn't compile in 10.0.16299.0, it does compile fine in 10.0.15063.0

**Comment by sasmaster** [comment]
Have the same issue here. It is weird because a couple of months ago it did compile with that version of the WinSDK. Now I downloaded the latest one from MS and it spits that error. Probably MS messed with the SDK. 
To the authors: Can we expect a patch for this one soon? If not,is it safe to rename CLIENT_ID because I see the error stems from the collision with similar named struct in WindowsSDK.
