### ISSUE TITLE
C++ Tutorials memory leaks!

### ISSUE THREAD

**Issue by zhaokaixs** [EasyHook/EasyHook#228]
The beep local hook e'g output:
Detected memory leaks!
Dumping objects ->
{90} normal block at 0x031D60A8, 16384 bytes long.
 Data: <            H   > 00 00 00 00 00 00 00 10 DF 84 A2 00 48 FA 0F 01 
Object dump complete.

**Comment by wenmu** [comment]
UnmanagedHook exsample output:
Detected memory leaks!
Dumping objects ->
Rtl\memory.c(127) : {77} normal block at 0x000002099A364940, 24576 bytes long.
 Data: <        c  B    > 00 00 00 00 00 00 00 10 63 12 C1 42 F7 7F 00 00 
Object dump complete.

**Comment by zhaokaixs** [comment]
It looks very bad. xD

**Comment by zhaokaixs** [comment]
It looks very bad. xD

**Comment by spazzarama** [comment]
@zhaokaixs & @wenmu  ok I have looked into this.

EasyHook32/64.dll performs some memory finalisation IF it is being unloaded by a final call to FreeLibrary (or ref count reaches in some other way). If the process is terminating, it correctly skips the memory freeing as the process will be cleaned up anyway AND it is best practice to not try to be too clever within DLL_PROCESS_DETACH especially during process termination - i.e. could result in exceptions, infinite loop or similar nasty. ([see this](https://blogs.msdn.microsoft.com/oldnewthing/20120105-00/?p=8683). 

Doing otherwise during process termination could introduce a crash on exit, or infinite loop under certain circumstances, instead of just a debug memory leak warning.

Therefore - in this circumstance the memory leak warnings of approx 16KB (that will only occur in visual studio during a debug session of the target process anyway) can and should be ignored.

Perhaps a future C++ (OOP) version of EasyHook could better manage this situation, but for now the current architecture gives us this constraint.
