### ISSUE TITLE
Is Kernel Hooks Compatible With PatchGuard

### ISSUE THREAD

**Issue by PhantomCloak** [EasyHook/EasyHook#230]
i do not use kernel hooks before but i decide to use but im not sure about hooks compatible with patchguard ?

**Comment by spazzarama** [comment]
EasyHook is no longer compatible with PatchGuard. There was an experimental version from a while back that worked around an older PatchGuard version. Therefore it cannot be used to hook Windows OS kernel mode methods protected by PatchGuard without disabling PatchGuard or bypassing it in some other way.

You are still able to hook non-Windows kernel mode methods (e.g. 3rd party kernel mode drivers etc), or any OS level kernel mode code not protected by PatchGuard.

**Comment by PhantomCloak** [comment]
thanks for reply but im little bit confused i understand that to this point cant hook kernel method e.g PsLookupProcessById but can i perform hook Nt functions like NtQueryInformationProcess

**Comment by spazzarama** [comment]
@PhantomCloak yes, you should be able to hook the Nt functions, best just to try one you have in mind. Not all methods will be hookable (there is a utility project in the source for checking which exports of a DLL are hookable).

**Comment by PhantomCloak** [comment]
i get it and i have a last question 😄  i wondering how it works EAC kernel hooking i mean as far as i know there is no method for directly hooking Nt functions i think EAC load hook dll to process with PsSetCreateProcessNotifyRoutine is that true ?

**Comment by spazzarama** [comment]
@PhantomCloak no idea how its done in EAC, but that is certainly a good starting point in order to get an early notification for a process and install any low-level protection etc...

Although you can't hook the kernel functions due to PatchGuard, I believe it is possible to reverse engineer the location of the notification callbacks stored in the callback queue as specified in previous calls to PsSetCreateProcessNotifyRoutine, and then hook those callbacks from a kernel mode driver. I remember reading something along these lines a while back but you would have to do further research to determine how/whether it is still possible.

**Comment by spazzarama** [comment]
@PhantomCloak sample code (that probably doesn't work) - found reference in a post somewhere. Use at own risk - but should provide a starting point for you.

https://pastebin.com/BjriqW4n
