### ISSUE TITLE
Target process crashed when using CreateAndInject

### ISSUE THREAD

**Issue by fl380** [EasyHook/EasyHook#324]
Hello,

I'm testing the C# remote filemon tutorial. When I use CreateandInject on some x64 targets, they crash with the following in event viewer

>Faulting application name: HelloWorld.exe, version: 1.0.0.0, time stamp: 0x5b8070e5
Faulting module name: clr.dll, version: 4.8.4121.0, time stamp: 0x5deabd50
Exception code: 0xc0000005
Fault offset: 0x0000000000077e08
Faulting process id: 0x5f08
Faulting application start time: 0x01d5e4dbbd4caad3
Faulting application path: F:\Documents\Visual Studio 2019\Injector\bin\x64\Debug\HelloWorld.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 62378d44-b17b-4302-957c-bad0aa51f8ae
Faulting package full name: 
Faulting package-relative application ID: 

No errors are passed to the injector. The hook seems to work if I hook into a running process but not with CreateAndInject. I've tried building the injector and hook as AnyCPU and x64 without success.

I'll be grateful for any help or suggestions please.

LATER:

I noticed that there were some changes to CreateAndInject in the dev branch. I've installed those files (v2.7.7339) but the same error occurs

**Comment by Alexr03** [comment]
Hey, did you manage to figure out what was causing this issue?

**Comment by mingpepe** [comment]
I encounter similar issue on x86 process. `CreateAndInject` cause remote process crash if remote process is written in C# and hook is not fired during clr init.

Workaround: hook something that will be called by clr init, e.g `CreateFileW`.

If executing a program normally, main thread will init clr, and associate main thread to managed thread via [EnsureEEStarted](https://github.com/dotnet/coreclr/blob/release/2.0.0/src/vm/ceemain.cpp#L320), the pointer to managed thread ([Thread](https://github.com/dotnet/coreclr/blob/release/2.0.0/src/vm/threads.h#L196) instance in CLR) will store in TLS. However, EE will only start once and check by [g_fEEStarted](https://github.com/dotnet/coreclr/blob/release/2.0.0/src/vm/ceemain.cpp#L277) which is not store in TLS but a global variable. By calling `CreateAndInject`, it will create a suspend process and create a remote thread and does some init for calling C# code. That's said, `EnsureEEStarted` is called on injected thread and `g_fEEStarted` will be set. So, when resume main thread, it will not start EE again, main thread will not associate with any managed thread (TLS slot will be empty). This is the root cause about crash.

Hooking `CreateFileW` works because it is called during clr init (before calling `EnsureEEStarted`). Calling managed code from native code is called reverse p/invoke, [that will create thread instance on CLR and associate with native thread.](https://github.com/dotnet/coreclr/blob/release/2.0.0/Documentation/botr/threading.md).
