### ISSUE TITLE
trouble with demo source code

### ISSUE THREAD

**Issue by 564064202** [EasyHook/EasyHook#61]
I'm having a trouble running the FileMon example. I downloaded the EasyHook source code and built the EasyHook.sln file. Then when I start the FileMon file with a specific process id it gives me the following exception.
 
Usage: FileMon %PID%
   or: FileMon PathToExecutable

Please enter a process Id or path to executable: 7724
There was an error while connecting to target:
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at EasyHook.WOW64Bypass.Install() in c:\Users\USER\Desktop\EasyHook-master\EasyHook\WOW64Bypass.cs:line 80
   at EasyHook.WOW64Bypass.Inject(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InRequireStrongName, Object[] InPassThruArgs) in c:\Users\USER\Desktop\EasyHook-master\EasyHook\WOW64Bypass.cs:line 104
   at EasyHook.RemoteHooking.InjectEx(Int32 InHostPID, Int32 InTargetPID, Int32 InWakeUpTID, Int32 InNativeOptions, String InLibraryPath_x86, String InLibraryPath_x64, Boolean InCanBypassWOW64, Boolean InCanCreateService, Boolean InRequireStrongName, Object[] InPassThruArgs) in c:\Users\USER\Desktop\EasyHook-master\EasyHook\RemoteHook.cs:line 689
   at EasyHook.RemoteHooking.Inject(Int32 InTargetPID, String InLibraryPath_x86, String InLibraryPath_x64, Object[] InPassThruArgs) in c:\Users\USER\Desktop\EasyHook-master\EasyHook\RemoteHook.cs:line 544
   at FileMon.Program.Main(String[] args) in c:\Users\USER\Desktop\EasyHook-master\Examples\FileMon\Program.cs:line 78
<Press any key to exit>
 

then I give put all missing dlls to the generated "netfx4-Debug\x64"
with your "EasyHook 2.7.5726.0 Binaries .NET 3.5/4.0 (zip)" 

but also failed.

[!see image](http://images2015.cnblogs.com/blog/83201/201601/83201-20160109094432590-984980288.png)
[! error code](http://images2015.cnblogs.com/blog/83201/201601/83201-20160109095353637-1982535044.png)

**Comment by 564064202** [comment]
dear sir,and I have a suggestion,
we need a detail Course about the latest version
easyhook .could you?

**Comment by 564064202** [comment]
The author seems to have never cared about us.

**Comment by spazzarama** [comment]
Try using build.bat as that puts all the correct outputs in the correct directories.

Btw - I'm on holidays so won't be able to help out much more than this for a bit

**Comment by 564064202** [comment]
@spazzarama  your holiday is too long....Ha-ha

**Comment by spazzarama** [comment]
My guess is that with the following error is because it could not find the easyhooksvc32/64.exe (depending on whether your app is 64-bit and trying to inject into 32-bit). Use the build.bat, read the build-me.txt file.

> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
> at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
> at EasyHook.WOW64Bypass.Install() in c:\Users\USER\Desktop\EasyHook-master\EasyHook\WOW64Bypass.cs:line 80

**Comment by 564064202** [comment]
then I put all missing dlls to the generated "netfx4-Debug\x64"
with your "EasyHook 2.7.5726.0 Binaries .NET 3.5/4.0 (zip)"

but also failed.

!see image
! error code

**Comment by spazzarama** [comment]
They have to be the correct version, if you are building again, you will need to make sure that the dll version references are ok. I suggest using the build.bat still, as that will ensure it all is the correct binaries being referenced.

**Comment by 564064202** [comment]
@spazzarama  thank you sir,i will try again.have a suggestion,
we need a detail Course about the latest version
easyhook .could you?

**Comment by spazzarama** [comment]
@564064202 it's been on my todo list for a long time... :(

**Comment by 564064202** [comment]
@spazzarama  ha-ha,may be your holiday is too long....haha

**Comment by 564064202** [comment]
@spazzarama sir, I'm in trouble again with bat(with MSBuild.Community.Tasks)

**Comment by spazzarama** [comment]
@564064202 the problem is the version of VS, just change v140 to whatever version of VS you are using.

**Comment by spazzarama** [comment]
@564064202 hmm, from the source code the platform toolset is v120 (VS 2013). What version of Visual Studio are you using?

If a later version, you may need to ensure all the projects are using v140, and then probably change the build.bat to use Microsoft Visual Studio 14.0 instead of Microsoft Visual Studio 12.0 in the following line: `call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64`

**Comment by 564064202** [comment]
@spazzarama sir,we need vs2015 supporting this project,
please,I beg you.........
We want your porject could run well in vs2012

**Comment by spazzarama** [comment]
@564064202 just update the projects to use v140 + the build.proj, build.bat etc... its not hard.

**Comment by 564064202** [comment]
@spazzarama sir,what dose "v140+build.proj" mean? 
Please forgive me for my stupidity
,I really don't know how to deal with it.

**Comment by spazzarama** [comment]
@564064202 lets go back to the start:

I believe the original issue is that you didn't have all the files you needed because you were building from source, but didn't build the entire solution (in both 64-bit and 32-bit).

You then copied binaries from website, however this won't work directly because the projects specify the version of the assemblies to load (you would need to change these project references).

All you need to do is build all the projects in the EasyHook.sln (right-click rebuild Solution) from Visual Studio is fine and you should be up and running.

Please try again from a clean clone.

Note: if you are building for 64-bit and want to be able to hook 32-bit you need to build twice, once for the 64-bit configuration and once for the 32-bit configuration, i.e. open Configuration Manager and select x64 then rebuild, then select Win32 and then rebuild.

![image](https://cloud.githubusercontent.com/assets/933730/13043783/7e69e7ce-d41e-11e5-9dbb-b58d25d60cda.png)
![image](https://cloud.githubusercontent.com/assets/933730/13043818/b25caba2-d41e-11e5-9a66-dc4921620d3c.png)

**Comment by spazzarama** [comment]
The build and packaging have been split into two build projects. Build.bat will now work with both VS 2013 and VS2014 without changes and also without installing the community build tasks package.
