### ISSUE TITLE
Question: How to know if LhInstallHook succeeded

### ISSUE THREAD

**Issue by WuZihong** [EasyHook/EasyHook#62]

**Comment by spazzarama** [comment]
Are you referring the native API or the .NET method?

In the native API it will return STATUS_SUCCESS for success. Otherwise, STATUS_NO_MEMORY (unable to find appropriate block of memory within range of target entry point), STATUS_NOT_SUPPORTED (the target entry point contains unsupported instructions) or STATUS_INSUFFICIENT_RESOURCES (too many hoks)

In the .NET wrapped method it will throw an exception if an error occurs.
