### ISSUE TITLE
RhCreateStealthRemoteThread

### ISSUE THREAD

**Issue by maddin123** [EasyHook/EasyHook#91]
After some tests "RhCreateStealthRemoteThread" should be renamed to "TerminateProcessWithDelay".

:-)

**Comment by spazzarama** [comment]
Nice :), I haven't tested that in a long time as I've never needed to use it, will have to revisit.

**Comment by spazzarama** [comment]
@maddin123 this "works" in 32-bit now. It is really hit and miss depending on what the thread you are targeting is for and/or doing. I think I may adjust so that it will prefer the thread you provide as a parameter, and then work through other threads if the specified one is unavailable or 0.

E.g. a thread with a message pump is going to work really well compared to a short-lived worker thread.
